(GH-54) Fix blocking Linux issue
On Windows building the command for chocolatey_command evaluates
environment variables, which causes the following issue:

```
Error: Could not autoload puppet/provider/package/chocolatey: undefined
method `+' for nil:NilClass
/var/lib/puppet/lib/puppet/provider/package/chocolatey.rb:24:in
`chocolatey_command'
/var/lib/puppet/lib/puppet/provider/package/chocolatey.rb:69:in `block
in <top (required)>'
```

Fix that to only evaluate on Windows. On Linux just evaluate to
'choco.exe'