Add env var to unit test
Commit 5c46d1e6 added a unit test that depends on an environment
variable, but the test raises an exception when the environment
variable does not exist.

Addresses:

    3) Puppet::Type::Package::ProviderChocolatey when fetching a package list should query chocolatey
    Failure/Error: commands=ENV['ChocolateyInstall'] + "/chocolateyInstall/chocolatey.cmd"
    NoMethodError:
    undefined method `+' for nil:NilClass
    # ./spec/unit/chocolatey_spec.rb:94